controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # Controller for Pulley A (Position)
    forward_position_controller:
      type: position_controllers/JointGroupPositionController

    # Controller for Pulley B (Currently Position, soon Torque)
    pulley_b_controller:
      type: position_controllers/JointGroupPositionController

forward_position_controller:
  ros__parameters:
    joints:
      - joint_pulley_A_x
      - joint_pulley_A_y
      - joint_pulley_A_z

pulley_b_controller:
  ros__parameters:
    joints:
      - joint_pulley_B_x
      - joint_pulley_B_y
      - joint_pulley_B_z